### PR TITLE
Release 4.1.0

### PR DESCRIPTION
**Pull request by newmana**

### CODE REVIEW

**Comment by bergmark** [comment]
Hi @newmana, I noticed that the 4.1.0 release was deprecated on hackage, but it's currently part of stackage nightly. What was the reason for the deprecation?

**Comment by newmana** [comment]
I can't see on hackage where it's listed as deprecated. Can you provide a link?

**Comment by bergmark** [comment]
https://hackage.haskell.org/package/geojson/preferred

**Comment by newmana** [comment]
That's fixed. Thanks for letting me know.

**Comment by bergmark** [comment]
thanks for clearing it up!

**Pull request merged**
